"""Generate docs/reference/conditions-and-actions.md from the code registries.

Run ``python -m scripts.gen_reference_docs --write`` to regenerate.
Run without ``--write`` to verify the committed doc is up to date (drift check);
exits 1 if stale.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml

# ---------------------------------------------------------------------------
# Condition registry — each class carries .name, .description, and optionally
# .predicate_help as class-level string attributes.  No HA runtime required.
# ---------------------------------------------------------------------------
from custom_components.ambience.conditions.day import DayCondition
from custom_components.ambience.conditions.people import PeopleCondition
from custom_components.ambience.conditions.script import ScriptCondition
from custom_components.ambience.conditions.state import StateCondition
from custom_components.ambience.conditions.sun import SunCondition
from custom_components.ambience.conditions.template import TemplateCondition
from custom_components.ambience.conditions.time_of_day import TimeOfDayCondition
from custom_components.ambience.conditions.weather import WeatherCondition

# Canonical condition class list — order here is the sort order in the doc
# (sorted alphabetically by .name at render time; this tuple is the registry).
CONDITION_CLASSES: tuple[type, ...] = (
    DayCondition,
    PeopleCondition,
    ScriptCondition,
    StateCondition,
    SunCondition,
    TemplateCondition,
    TimeOfDayCondition,
    WeatherCondition,
)

_SERVICES_YAML = Path(__file__).parent.parent / "custom_components/ambience/services.yaml"

DOC_PATH = Path("docs/reference/conditions-and-actions.md")
HEADER = "<!-- GENERATED by scripts/gen_reference_docs.py — do not edit by hand -->\n"


def _load_services() -> dict[str, Any]:
    """Load ambience/services.yaml and return the raw dict."""
    return yaml.safe_load(_SERVICES_YAML.read_text()) or {}


def render_reference() -> str:
    """Render the full reference document and return it as a string."""
    lines: list[str] = [
        HEADER,
        "# Conditions and Actions Reference",
        "",
        "This document is auto-generated from the code registries.",
        "To regenerate: `python -m scripts.gen_reference_docs --write`",
        "",
        "## Conditions",
        "",
        "Built-in conditions that can be used in Ambience rules.",
        "Each condition is referenced by its **kind** key in the `when` clause of a rule.",
        "",
    ]

    for cls in sorted(CONDITION_CLASSES, key=lambda c: c.name):
        lines.append(f"### {cls.name}")
        lines.append("")
        lines.append(cls.description)
        predicate_help = getattr(cls, "predicate_help", None)
        if predicate_help:
            lines.append("")
            lines.append(f"**Predicate shape:** {predicate_help}")
        lines.append("")

    lines += [
        "## Ambience actions",
        "",
        "Services registered by the Ambience integration.",
        "",
    ]

    services = _load_services()
    for action_name in sorted(services.keys()):
        spec = services[action_name]
        lines.append(f"### ambience.{action_name}")
        lines.append("")
        if isinstance(spec, dict):
            name = spec.get("name", "")
            description = spec.get("description", "")
            if name:
                lines.append(f"**Name:** {name}")
                lines.append("")
            if description:
                lines.append(description)
                lines.append("")
            fields = spec.get("fields", {})
            if fields:
                lines.append("**Fields:**")
                lines.append("")
                for field_name in sorted(fields.keys()):
                    field = fields[field_name]
                    if isinstance(field, dict):
                        field_desc = field.get("description", "")
                        required = field.get("required", False)
                        req_label = " *(required)*" if required else " *(optional)*"
                        lines.append(f"- `{field_name}`{req_label}: {field_desc}")
                    else:
                        lines.append(f"- `{field_name}`")
                lines.append("")

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate or drift-check docs/reference/conditions-and-actions.md"
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write the generated doc to disk (regenerate).",
    )
    args = parser.parse_args(argv)
    content = render_reference()
    if args.write:
        DOC_PATH.parent.mkdir(parents=True, exist_ok=True)
        DOC_PATH.write_text(content)
        print(f"Wrote {DOC_PATH}")
        return 0
    current = DOC_PATH.read_text() if DOC_PATH.exists() else ""
    if current != content:
        print("DOCS DRIFT: docs/reference/conditions-and-actions.md is stale.")
        print("Run: python -m scripts.gen_reference_docs --write && commit the result.")
        return 1
    print("Docs reference up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
